-- GROUPS
INSERT INTO food_group (id, description) VALUES (1, "Produtos de panificação, cereais, leguminosas, raizes e tubérculos, e seus derivados");
INSERT INTO food_group (id, description) VALUES (2, "Verduras, hortaliças e conservas vegetais");
INSERT INTO food_group (id, description) VALUES (3, "Frutas, sucos, nectars e refrescos de frutas");
INSERT INTO food_group (id, description) VALUES (4, "Leite e derivados");
INSERT INTO food_group (id, description) VALUES (5, "Carnes e ovos");
INSERT INTO food_group (id, description) VALUES (6, "Óleos, gorduras e sementes oleaginosas");
INSERT INTO food_group (id, description) VALUES (7, "Açúcares e produtos com energia proveniente de carboidratos e gorduras");
INSERT INTO food_group (id, description) VALUES (8, "Molhos, temperos prontos, caldos, sopas e pratos preparados");

--SUBGROUPS
INSERT INTO food_subgroup (id, group_id, description) VALUES (1, 1, "Amidos e féculas");
INSERT INTO food_subgroup (id, group_id, description) VALUES (2, 1, "Arroz cru");
INSERT INTO food_subgroup (id, group_id, description) VALUES (3, 1, "Aveia em flocos sem outros ingredientes");
INSERT INTO food_subgroup (id, group_id, description) VALUES (4, 1, "Barra de cereais com até 10% de gordura");
INSERT INTO food_subgroup (id, group_id, description) VALUES (5, 1, "Batata, mandioca e outros tubérculos, cozidos em água, embalados à vácuo");
INSERT INTO food_subgroup (id, group_id, description) VALUES (6, 1, "Batata e mandioca pré-frita congelada");
INSERT INTO food_subgroup (id, group_id, description) VALUES (7, 1, "Produtos a base de tubérculos e cereais pré-fritos e ou congelados");
INSERT INTO food_subgroup (id, group_id, description) VALUES (8, 1, "Biscoito salgados, integrais e grissines");
INSERT INTO food_subgroup (id, group_id, description) VALUES (9, 1, "Bolos, todos os tipos sem recheio");
INSERT INTO food_subgroup (id, group_id, description) VALUES (10, 1, "Canjica (grão cru)");
INSERT INTO food_subgroup (id, group_id, description) VALUES (11, 1, "Cereal matinal pesando até 45g por xícara - leves");
INSERT INTO food_subgroup (id, group_id, description) VALUES (12, 1, "Cereal matinal pesando mais do que 45 g por xícara");
INSERT INTO food_subgroup (id, group_id, description) VALUES (13, 1, "Cereais integrais crus");
INSERT INTO food_subgroup (id, group_id, description) VALUES (14, 1, "Farinhas de cereais e tubérculos, todos os tipos");
INSERT INTO food_subgroup (id, group_id, description) VALUES (15, 1, "Farelo de cereais e germe de trigo");
INSERT INTO food_subgroup (id, group_id, description) VALUES (16, 1, "Farinha Láctea");
INSERT INTO food_subgroup (id, group_id, description) VALUES (17, 1, "Farofa pronta");
INSERT INTO food_subgroup (id, group_id, description) VALUES (18, 1, "Massa alimentícia seca");
INSERT INTO food_subgroup (id, group_id, description) VALUES (19, 1, "Massa desidratada com recheio");
INSERT INTO food_subgroup (id, group_id, description) VALUES (20, 1, "Massas frescas com e sem recheios");
INSERT INTO food_subgroup (id, group_id, description) VALUES (21, 1, "Pães embalados fatiados ou não, com ou sem recheio");
INSERT INTO food_subgroup (id, group_id, description) VALUES (22, 1, "Pães embalados de consumo individual, chipa paraguaia");
INSERT INTO food_subgroup (id, group_id, description) VALUES (23, 1, "Pão doce sem frutas");
INSERT INTO food_subgroup (id, group_id, description) VALUES (24, 1, "Pão croissant, outros produtos de panificação, salgados ou doces sem recheio");
INSERT INTO food_subgroup (id, group_id, description) VALUES (25, 1, "Pão de batata, pão de queijo e outros resfriados e congelados com recheio e massas para pães");
INSERT INTO food_subgroup (id, group_id, description) VALUES (26, 1, "Pão de batata, pão de queijo e outros resfriados e congelados sem recheio, chipa paraguaia");
INSERT INTO food_subgroup (id, group_id, description) VALUES (27, 1, "Pipoca");
INSERT INTO food_subgroup (id, group_id, description) VALUES (28, 1, "Torradas");
INSERT INTO food_subgroup (id, group_id, description) VALUES (29, 1, "Tofu");
INSERT INTO food_subgroup (id, group_id, description) VALUES (30, 1, "Trigo para kibe e proteína texturizada de soja");
INSERT INTO food_subgroup (id, group_id, description) VALUES (31, 1, "Leguminosas secas, todas");
INSERT INTO food_subgroup (id, group_id, description) VALUES (32, 1, "Pós para preparar flans e sobremesas");
INSERT INTO food_subgroup (id, group_id, description) VALUES (33, 1, "Sagu");
INSERT INTO food_subgroup (id, group_id, description) VALUES (34, 1, "Massas para pasteis e panquecas");
INSERT INTO food_subgroup (id, group_id, description) VALUES (35, 1, "Massa para tortas salgadas");
INSERT INTO food_subgroup (id, group_id, description) VALUES (36, 1, "Massa para pizza");
INSERT INTO food_subgroup (id, group_id, description) VALUES (37, 1, "Farinha de rosca");
INSERT INTO food_subgroup (id, group_id, description) VALUES (38, 1, "Preparações a base de soja tipo: milanesa almôndegas e hambúrguer");
INSERT INTO food_subgroup (id, group_id, description) VALUES (39, 1, "Mistura para sopa paraguaia y chipaguazú");
INSERT INTO food_subgroup (id, group_id, description) VALUES (40, 1, "Pré-mistura para preparar bori-bori");
INSERT INTO food_subgroup (id, group_id, description) VALUES (41, 1, "Pré-mistura para preparar chipa paraguaia e mbeyu e outros pães");
INSERT INTO food_subgroup (id, group_id, description) VALUES (42, 1, "Preparado desidratados para purês de tubérculos");
INSERT INTO food_subgroup (id, group_id, description) VALUES (43, 1, "Pós para preparar bolos e tortas");

INSERT INTO food_subgroup (id, group_id, description) VALUES (1, 2, "Concentrado de vegetais triplo, (extrato)");
INSERT INTO food_subgroup (id, group_id, description) VALUES (2, 2, "Concentrado de vegetais");
INSERT INTO food_subgroup (id, group_id, description) VALUES (3, 2, "Purê ou polpa de vegetais, incluindo tomate");
INSERT INTO food_subgroup (id, group_id, description) VALUES (4, 2, "Molho de tomate ou a base de tomate e outros vegetais");
INSERT INTO food_subgroup (id, group_id, description) VALUES (5, 2, "Picles e alcaparras");
INSERT INTO food_subgroup (id, group_id, description) VALUES (6, 2, "Sucos de vegetais, frutas e sojas");
INSERT INTO food_subgroup (id, group_id, description) VALUES (7, 2, "Vegetais desidratados em conserva (tomate seco)");
INSERT INTO food_subgroup (id, group_id, description) VALUES (8, 2, "Vegetais desidratados para sopa");
INSERT INTO food_subgroup (id, group_id, description) VALUES (9, 2, "Vegetais desidratados para purê");
INSERT INTO food_subgroup (id, group_id, description) VALUES (10, 2, "Vegetais em conserva (alcachofra, aspargo, cogumelos, pimentão, pepino e palmito) em salmoura, vinagre e azeite");
INSERT INTO food_subgroup (id, group_id, description) VALUES (11, 2, "Jardineira e outras conservas de vegetais e legumes (cenouras, ervilhas, milho, tomate pelado)");
INSERT INTO food_subgroup (id, group_id, description) VALUES (12, 2, "Vegetais empanados");

INSERT INTO food_subgroup (id, group_id, description) VALUES (1, 3, "Polpa de frutas para refresco, sucos concentrados de frutas e desidratados");
INSERT INTO food_subgroup (id, group_id, description) VALUES (2, 3, "Polpa de frutas para sobremesas");
INSERT INTO food_subgroup (id, group_id, description) VALUES (3, 3, "Suco, néctar e bebidas de frutas");
INSERT INTO food_subgroup (id, group_id, description) VALUES (4, 3, "Frutas desidratadas (peras, pêssegos, abacaxi, ameixas, partes comestíveis)");
INSERT INTO food_subgroup (id, group_id, description) VALUES (5, 3, "Uva passa");
INSERT INTO food_subgroup (id, group_id, description) VALUES (6, 3, "Fruta em conserva, incluindo salada de frutas");

INSERT INTO food_subgroup (id, group_id, description) VALUES (1, 4, "Bebida láctea");
INSERT INTO food_subgroup (id, group_id, description) VALUES (2, 4, "Leites fermentados, iogurte, todos os tipos");
INSERT INTO food_subgroup (id, group_id, description) VALUES (3, 4, "Leite fluido, todos os tipos");
INSERT INTO food_subgroup (id, group_id, description) VALUES (4, 4, "Leite evaporado");
INSERT INTO food_subgroup (id, group_id, description) VALUES (5, 4, "Queijo ralado");
INSERT INTO food_subgroup (id, group_id, description) VALUES (6, 4, "Queijo cottage, ricota desnatado, queijo minas, requeijão desnatado e petit-suisse");
INSERT INTO food_subgroup (id, group_id, description) VALUES (7, 4, "Outros queijos (ricota, semi-duros, branco, requeijão, queijo cremoso, fundidos e em pasta)");
INSERT INTO food_subgroup (id, group_id, description) VALUES (8, 4, "Leite em pó");
INSERT INTO food_subgroup (id, group_id, description) VALUES (9, 4, "Sobremesas Lácteas");
INSERT INTO food_subgroup (id, group_id, description) VALUES (10, 4, "Pós para preparar sobremesas lácteas");
INSERT INTO food_subgroup (id, group_id, description) VALUES (11, 4, "Pós para preparar sorvetes");

INSERT INTO food_subgroup (id, group_id, description) VALUES (1, 5, "Almôndegas a base de carnes");
INSERT INTO food_subgroup (id, group_id, description) VALUES (2, 5, "Anchovas em conserva");
INSERT INTO food_subgroup (id, group_id, description) VALUES (3, 5, "Apresuntado e Corned Beef");
INSERT INTO food_subgroup (id, group_id, description) VALUES (4, 5, "Atum, sardinha, pescado, mariscos, outros peixes em conserva com ou sem molhos");
INSERT INTO food_subgroup (id, group_id, description) VALUES (5, 5, "Caviar");
INSERT INTO food_subgroup (id, group_id, description) VALUES (6, 5, "Charque");
INSERT INTO food_subgroup (id, group_id, description) VALUES (7, 5, "Hambúrguer a base de carnes");
INSERT INTO food_subgroup (id, group_id, description) VALUES (8, 5, "Linguiça, salsicha, todos os tipos");
INSERT INTO food_subgroup (id, group_id, description) VALUES (9, 5, "Kani-kama");
INSERT INTO food_subgroup (id, group_id, description) VALUES (10, 5, "Preparações de carnes temperadas, defumadas, cozidas ou não");
INSERT INTO food_subgroup (id, group_id, description) VALUES (11, 5, "Preparações de carnes com farinhas ou empanadas");
INSERT INTO food_subgroup (id, group_id, description) VALUES (12, 5, "Embutidos, fiambre e presunto");
INSERT INTO food_subgroup (id, group_id, description) VALUES (13, 5, "Peito de peru, blanquet");
INSERT INTO food_subgroup (id, group_id, description) VALUES (14, 5, "Patês (presunto, fígado e bacon, etc..)");
INSERT INTO food_subgroup (id, group_id, description) VALUES (15, 5, "Ovo");

INSERT INTO food_subgroup (id, group_id, description) VALUES (1, 6, "Óleos vegetais, todos os tipos");
INSERT INTO food_subgroup (id, group_id, description) VALUES (2, 6, "Azeitona");
INSERT INTO food_subgroup (id, group_id, description) VALUES (3, 6, "Bacon em pedaços - defumado ou fresco");
INSERT INTO food_subgroup (id, group_id, description) VALUES (4, 6, "Banha e gorduras animais");
INSERT INTO food_subgroup (id, group_id, description) VALUES (5, 6, "Gordura vegetal");
INSERT INTO food_subgroup (id, group_id, description) VALUES (6, 6, "Maionese e molhos a base de maionese");
INSERT INTO food_subgroup (id, group_id, description) VALUES (7, 6, "Manteiga, margarina e similares");
INSERT INTO food_subgroup (id, group_id, description) VALUES (8, 6, "Molhos para saladas a base de óleo (todos os tipos)");
INSERT INTO food_subgroup (id, group_id, description) VALUES (9, 6, "Chantilly");
INSERT INTO food_subgroup (id, group_id, description) VALUES (10, 6, "Creme de leite");
INSERT INTO food_subgroup (id, group_id, description) VALUES (11, 6, "Leite de coco");
INSERT INTO food_subgroup (id, group_id, description) VALUES (12, 6, "Coco ralado");
INSERT INTO food_subgroup (id, group_id, description) VALUES (13, 6, "Sementes oleaginosas (misturadas, cortadas, picadas, inteiras)");

INSERT INTO food_subgroup (id, group_id, description) VALUES (1, 7, "Açúcar, todos os tipos");
INSERT INTO food_subgroup (id, group_id, description) VALUES (2, 7, "Achocolatado em pó, pós com base de cacau, chocolate em pó e cacau em pó");
INSERT INTO food_subgroup (id, group_id, description) VALUES (3, 7, "Doces em corte (goiaba, marmelo, figo, batata, etc)");
INSERT INTO food_subgroup (id, group_id, description) VALUES (4, 7, "Doces em pasta (abóbora, goiaba, leite, banana, mocotó)");
INSERT INTO food_subgroup (id, group_id, description) VALUES (5, 7, "Geleias diversas");
INSERT INTO food_subgroup (id, group_id, description) VALUES (6, 7, "Glucose de milho, mel, melado, cobertura de frutas, leite condensado e outros xaropes (cassis, groselha, framboesa, amora, guaraná etc)");
INSERT INTO food_subgroup (id, group_id, description) VALUES (7, 7, "Pó para gelatina");
INSERT INTO food_subgroup (id, group_id, description) VALUES (8, 7, "Sobremesa de gelatina pronta");
INSERT INTO food_subgroup (id, group_id, description) VALUES (9, 7, "Frutas inteiras em conserva para adornos (cereja maraschino, framboesa)");
INSERT INTO food_subgroup (id, group_id, description) VALUES (10, 7, "Balas, pirulitos e pastilhas");
INSERT INTO food_subgroup (id, group_id, description) VALUES (11, 7, "Goma de mascar");
INSERT INTO food_subgroup (id, group_id, description) VALUES (12, 7, "Chocolates, bombons e similares");
INSERT INTO food_subgroup (id, group_id, description) VALUES (13, 7, "Confeitos de chocolate e drageados em geral");
INSERT INTO food_subgroup (id, group_id, description) VALUES (14, 7, "Sorvetes de massa");
INSERT INTO food_subgroup (id, group_id, description) VALUES (15, 7, "Sorvetes individuais");
INSERT INTO food_subgroup (id, group_id, description) VALUES (16, 7, "Barra de cereais com mais de 10% de gorduras, torrones, pé de moleque e paçoca");
INSERT INTO food_subgroup (id, group_id, description) VALUES (17, 7, "Bebidas não alcoólicas, carbonatadas ou não (chás, bebidas a base de soja e refrigerantes)");
INSERT INTO food_subgroup (id, group_id, description) VALUES (18, 7, "Pós para preparo de refresco");
INSERT INTO food_subgroup (id, group_id, description) VALUES (19, 7, "Biscoito doce, com ou sem recheio");
INSERT INTO food_subgroup (id, group_id, description) VALUES (20, 7, "Brownies e alfajores");
INSERT INTO food_subgroup (id, group_id, description) VALUES (21, 7, "Frutas cristalizadas");
INSERT INTO food_subgroup (id, group_id, description) VALUES (22, 7, "Panettone");
INSERT INTO food_subgroup (id, group_id, description) VALUES (23, 7, "Bolo com frutas");
INSERT INTO food_subgroup (id, group_id, description) VALUES (24, 7, "Bolos e similares com recheio e/ou cobertura");
INSERT INTO food_subgroup (id, group_id, description) VALUES (25, 7, "Pão croissant, produtos de panificação, salgados ou doces com recheio e ou cobertura");
INSERT INTO food_subgroup (id, group_id, description) VALUES (26, 7, "Snacks a base de cereais e farinhas para petisco");
INSERT INTO food_subgroup (id, group_id, description) VALUES (27, 7, "Mistura para preparo de docinho, cobertura para bolos, tortas e sorvetes, etc.");

INSERT INTO food_subgroup (id, group_id, description) VALUES (1, 8, "Caldo (carne, galinha, legumes, etc) e pós para sopa incluindo (bori-bori, pirá caldo, soyo)");
INSERT INTO food_subgroup (id, group_id, description) VALUES (2, 8, "Catchup e mostarda");
INSERT INTO food_subgroup (id, group_id, description) VALUES (3, 8, "Molhos a base de soja e ou vinagre");
INSERT INTO food_subgroup (id, group_id, description) VALUES (4, 8, "Molhos a base de produtos lácteos ou caldos");
INSERT INTO food_subgroup (id, group_id, description) VALUES (5, 8, "Pós para preparar molhos");
INSERT INTO food_subgroup (id, group_id, description) VALUES (6, 8, "Misso");
INSERT INTO food_subgroup (id, group_id, description) VALUES (7, 8, "Missoshiro");
INSERT INTO food_subgroup (id, group_id, description) VALUES (8, 8, "Extrato de soja");
INSERT INTO food_subgroup (id, group_id, description) VALUES (9, 8, "Pratos preparados prontos e semiprontos não incluídos em outros itens da tabela");
INSERT INTO food_subgroup (id, group_id, description) VALUES (10, 8, "Temperos completos");