-- GROUPS
INSERT INTO food_group (id, description, description_filter) VALUES (1, "PRODUTOS DE PANIFICAÇÃO, CEREAIS, LEGUMINOSAS, RAIZES E TUBÉRCULOS, E SEUS DERIVADOS", "produtos de panificacao, cereais, leguminosas, raizes e tuberculos, e seus derivados");
INSERT INTO food_group (id, description, description_filter) VALUES (2, "VERDURAS, HORTALIÇAS E CONSERVAS VEGETAIS", "verduras, hortalicas e conservas vegetais");
INSERT INTO food_group (id, description, description_filter) VALUES (3, "FRUTAS, SUCOS, NECTARS E REFRESCOS DE FRUTAS", "frutas, sucos, nectars e refrescos de frutas");
INSERT INTO food_group (id, description, description_filter) VALUES (4, "LEITE E DERIVADOS", "leite e derivados");
INSERT INTO food_group (id, description, description_filter) VALUES (5, "CARNES E OVOS", "carnes e ovos");
INSERT INTO food_group (id, description, description_filter) VALUES (6, "ÓLEOS, GORDURAS E SEMENTES OLEAGINOSAS", "oleos, gorduras e sementes oleaginosas");
INSERT INTO food_group (id, description, description_filter) VALUES (7, "AÇÚCARES E PRODUTOS COM ENERGIA PROVENIENTE DE CARBOIDRATOS E GORDURAS", "acucares e produtos com energia proveniente de carboidratos e gorduras");
INSERT INTO food_group (id, description, description_filter) VALUES (8, "MOLHOS, TEMPEROS PRONTOS, CALDOS, SOPAS E PRATOS PREPARADOS", "molhos, temperos prontos, caldos, sopas e pratos preparados");

--SUBGROUPS
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (1, 1, "Amidos e féculas", "amidos e feculas");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (2, 1, "Arroz cru", "arroz cru");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (3, 1, "Aveia em flocos sem outros ingredientes", "aveia em flocos sem outros ingredientes");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (4, 1, "Barra de cereais com até 10% de gordura", "barra de cereais com ate 10% de gordura");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (5, 1, "Batata, mandioca e outros tubérculos, cozidos em água, embalados à vácuo", "batata, mandioca e outros tuberculos, cozidos em agua, embalados a vacuo");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (6, 1, "Batata e mandioca pré-frita congelada", "batata e mandioca pre-frita congelada");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (7, 1, "Produtos a base de tubérculos e cereais pré-fritos e ou congelados", "produtos a base de tuberculos e cereais pre-fritos e ou congelados");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (8, 1, "Biscoito salgados, integrais e grissines", "biscoito salgados, integrais e grissines");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (9, 1, "Bolos, todos os tipos sem recheio", "bolos, todos os tipos sem recheio");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (10, 1, "Canjica (grão cru)", "canjica (grao cru)");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (11, 1, "Cereal matinal pesando até 45g por xícara - leves", "cereal matinal pesando ate 45g por xicara - leves");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (12, 1, "Cereal matinal pesando mais do que 45 g por xícara", "cereal matinal pesando mais do que 45 g por xicara");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (13, 1, "Cereais integrais crus", "cereais integrais crus");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (14, 1, "Farinhas de cereais e tubérculos, todos os tipos", "farinhas de cereais e tuberculos, todos os tipos");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (15, 1, "Farelo de cereais e germe de trigo", "farelo de cereais e germe de trigo");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (16, 1, "Farinha Láctea", "farinha lactea");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (17, 1, "Farofa pronta", "farofa pronta");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (18, 1, "Massa alimentícia seca", "massa alimenticia seca");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (19, 1, "Massa desidratada com recheio", "massa desidratada com recheio");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (20, 1, "Massas frescas com e sem recheios", "massas frescas com e sem recheios");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (21, 1, "Pães embalados fatiados ou não, com ou sem recheio", "paes embalados fatiados ou nao, com ou sem recheio");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (22, 1, "Pães embalados de consumo individual, chipa paraguaia", "paes embalados de consumo individual, chipa paraguaia");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (23, 1, "Pão doce sem frutas", "pao doce sem frutas");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (24, 1, "Pão croissant, outros produtos de panificação, salgados ou doces sem recheio", "pao croissant, outros produtos de panificacao, salgados ou doces sem recheio");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (25, 1, "Pão de batata, pão de queijo e outros resfriados e congelados com recheio e massas para pães", "pao de batata, pao de queijo e outros resfriados e congelados com recheio e massas para paes");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (26, 1, "Pão de batata, pão de queijo e outros resfriados e congelados sem recheio, chipa paraguaia", "pao de batata, pao de queijo e outros resfriados e congelados sem recheio, chipa paraguaia");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (27, 1, "Pipoca", "pipoca");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (28, 1, "Torradas", "torradas");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (29, 1, "Tofu", "tofu");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (30, 1, "Trigo para kibe e proteína texturizada de soja", "trigo para kibe e proteina texturizada de soja");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (31, 1, "Leguminosas secas, todas", "leguminosas secas, todas");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (32, 1, "Pós para preparar flans e sobremesas", "pos para preparar flans e sobremesas");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (33, 1, "Sagu", "sagu");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (34, 1, "Massas para pasteis e panquecas", "massas para pasteis e panquecas");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (35, 1, "Massa para tortas salgadas", "massa para tortas salgadas");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (36, 1, "Massa para pizza", "massa para pizza");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (37, 1, "Farinha de rosca", "farinha de rosca");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (38, 1, "Preparações a base de soja tipo: milanesa almôndegas e hambúrguer", "preparacoes a base de soja tipo: milanesa almondegas e hamburguer");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (39, 1, "Mistura para sopa paraguaia y chipaguazú", "mistura para sopa paraguaia y chipaguazu");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (40, 1, "Pré-mistura para preparar bori-bori", "pre-mistura para preparar bori-bori");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (41, 1, "Pré-mistura para preparar chipa paraguaia e mbeyu e outros pães", "pre-mistura para preparar chipa paraguaia e mbeyu e outros paes");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (42, 1, "Preparado desidratados para purês de tubérculos", "preparado desidratados para pures de tuberculos");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (43, 1, "Pós para preparar bolos e tortas", "pos para preparar bolos e tortas");

INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (1, 2, "Concentrado de vegetais triplo, (extrato)", "concentrado de vegetais triplo, (extrato)");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (2, 2, "Concentrado de vegetais", "concentrado de vegetais");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (3, 2, "Purê ou polpa de vegetais, incluindo tomate", "pure ou polpa de vegetais, incluindo tomate");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (4, 2, "Molho de tomate ou a base de tomate e outros vegetais", "molho de tomate ou a base de tomate e outros vegetais");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (5, 2, "Picles e alcaparras", "picles e alcaparras");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (6, 2, "Sucos de vegetais, frutas e sojas", "sucos de vegetais, frutas e sojas");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (7, 2, "Vegetais desidratados em conserva (tomate seco)", "vegetais desidratados em conserva (tomate seco)");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (8, 2, "Vegetais desidratados para sopa", "vegetais desidratados para sopa");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (9, 2, "Vegetais desidratados para purê", "vegetais desidratados para pure");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (10, 2, "Vegetais em conserva (alcachofra, aspargo, cogumelos, pimentão, pepino e palmito) em salmoura, vinagre e azeite", "vegetais em conserva (alcachofra, aspargo, cogumelos, pimentao, pepino e palmito) em salmoura, vinagre e azeite");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (11, 2, "Jardineira e outras conservas de vegetais e legumes (cenouras, ervilhas, milho, tomate pelado)", "jardineira e outras conservas de vegetais e legumes (cenouras, ervilhas, milho, tomate pelado)");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (12, 2, "Vegetais empanados", "vegetais empanados");

INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (1, 3, "Polpa de frutas para refresco, sucos concentrados de frutas e desidratados", "polpa de frutas para refresco, sucos concentrados de frutas e desidratados");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (2, 3, "Polpa de frutas para sobremesas", "polpa de frutas para sobremesas");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (3, 3, "Suco, néctar e bebidas de frutas", "suco, nectar e bebidas de frutas");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (4, 3, "Frutas desidratadas (peras, pêssegos, abacaxi, ameixas, partes comestíveis)", "frutas desidratadas (peras, pessegos, abacaxi, ameixas, partes comestiveis)");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (5, 3, "Uva passa", "uva passa");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (6, 3, "Fruta em conserva, incluindo salada de frutas", "fruta em conserva, incluindo salada de frutas");

INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (1, 4, "Bebida láctea", "bebida lactea");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (2, 4, "Leites fermentados, iogurte, todos os tipos", "leites fermentados, iogurte, todos os tipos");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (3, 4, "Leite fluido, todos os tipos", "leite fluido, todos os tipos");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (4, 4, "Leite evaporado", "leite evaporado");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (5, 4, "Queijo ralado", "queijo ralado");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (6, 4, "Queijo cottage, ricota desnatado, queijo minas, requeijão desnatado e petit-suisse", "queijo cottage, ricota desnatado, queijo minas, requeijao desnatado e petit-suisse");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (7, 4, "Outros queijos (ricota, semi-duros, branco, requeijão, queijo cremoso, fundidos e em pasta)", "outros queijos (ricota, semi-duros, branco, requeijao, queijo cremoso, fundidos e em pasta)");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (8, 4, "Leite em pó", "leite em po");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (9, 4, "Sobremesas Lácteas", "sobremesas lacteas");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (10, 4, "Pós para preparar sobremesas lácteas", "pos para preparar sobremesas lacteas");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (11, 4, "Pós para preparar sorvetes", "pos para preparar sorvetes");

INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (1, 5, "Almôndegas a base de carnes", "almondegas a base de carnes");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (2, 5, "Anchovas em conserva", "anchovas em conserva");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (3, 5, "Apresuntado e Corned Beef", "apresuntado e corned beef");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (4, 5, "Atum, sardinha, pescado, mariscos, outros peixes em conserva com ou sem molhos", "atum, sardinha, pescado, mariscos, outros peixes em conserva com ou sem molhos");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (5, 5, "Caviar", "caviar");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (6, 5, "Charque", "charque");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (7, 5, "Hambúrguer a base de carnes", "hamburguer a base de carnes");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (8, 5, "Linguiça, salsicha, todos os tipos", "linguica, salsicha, todos os tipos");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (9, 5, "Kani-kama", "kani-kama");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (10, 5, "Preparações de carnes temperadas, defumadas, cozidas ou não", "preparacoes de carnes temperadas, defumadas, cozidas ou nao");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (11, 5, "Preparações de carnes com farinhas ou empanadas", "preparações de carnes com farinhas ou empanadas");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (12, 5, "Embutidos, fiambre e presunto", "embutidos, fiambre e presunto");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (13, 5, "Peito de peru, blanquet", "peito de peru, blanquet");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (14, 5, "Patês (presunto, fígado e bacon, etc..)", "pates (presunto, figado e bacon, etc..)");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (15, 5, "Ovo", "ovo");

INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (1, 6, "Óleos vegetais, todos os tipos", "oleos vegetais, todos os tipos");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (2, 6, "Azeitona", "azeitona");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (3, 6, "Bacon em pedaços - defumado ou fresco", "bacon em pedacos - defumado ou fresco");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (4, 6, "Banha e gorduras animais", "banha e gorduras animais");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (5, 6, "Gordura vegetal", "gordura vegetal");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (6, 6, "Maionese e molhos a base de maionese", "maionese e molhos a base de maionese");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (7, 6, "Manteiga, margarina e similares", "manteiga, margarina e similares");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (8, 6, "Molhos para saladas a base de óleo (todos os tipos)", "molhos para saladas a base de oleo (todos os tipos)");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (9, 6, "Chantilly", "chantilly");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (10, 6, "Creme de leite", "creme de leite");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (11, 6, "Leite de coco", "leite de coco");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (12, 6, "Coco ralado", "coco ralado");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (13, 6, "Sementes oleaginosas (misturadas, cortadas, picadas, inteiras)", "sementes oleaginosas (misturadas, cortadas, picadas, inteiras)");

INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (1, 7, "Açúcar, todos os tipos", "acucar, todos os tipos");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (2, 7, "Achocolatado em pó, pós com base de cacau, chocolate em pó e cacau em pó", "achocolatado em po, pos com base de cacau, chocolate em po e cacau em po");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (3, 7, "Doces em corte (goiaba, marmelo, figo, batata, etc)", "doces em corte (goiaba, marmelo, figo, batata, etc)");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (4, 7, "Doces em pasta (abóbora, goiaba, leite, banana, mocotó)", "doces em pasta (abobora, goiaba, leite, banana, mocoto)");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (5, 7, "Geleias diversas", "geleias diversas");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (6, 7, "Glucose de milho, mel, melado, cobertura de frutas, leite condensado e outros xaropes (cassis, groselha, framboesa, amora, guaraná etc)", "glucose de milho, mel, melado, cobertura de frutas, leite condensado e outros xaropes (cassis, groselha, framboesa, amora, guarana etc)");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (7, 7, "Pó para gelatina", "po para gelatina");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (8, 7, "Sobremesa de gelatina pronta", "sobremesa de gelatina pronta");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (9, 7, "Frutas inteiras em conserva para adornos (cereja maraschino, framboesa)", "frutas inteiras em conserva para adornos (cereja maraschino, framboesa)");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (10, 7, "Balas, pirulitos e pastilhas", "balas, pirulitos e pastilhas");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (11, 7, "Goma de mascar", "goma de mascar");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (12, 7, "Chocolates, bombons e similares", "chocolates, bombons e similares");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (13, 7, "Confeitos de chocolate e drageados em geral", "confeitos de chocolate e drageados em geral");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (14, 7, "Sorvetes de massa", "sorvetes de massa");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (15, 7, "Sorvetes individuais", "sorvetes individuais");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (16, 7, "Barra de cereais com mais de 10% de gorduras, torrones, pé de moleque e paçoca", "barra de cereais com mais de 10% de gorduras, torrones, pe de moleque e paçoca");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (17, 7, "Bebidas não alcoólicas, carbonatadas ou não (chás, bebidas a base de soja e refrigerantes)", "bebidas nao alcoolicas, carbonatadas ou nao (chas, bebidas a base de soja e refrigerantes)");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (18, 7, "Pós para preparo de refresco", "pos para preparo de refresco");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (19, 7, "Biscoito doce, com ou sem recheio", "biscoito doce, com ou sem recheio");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (20, 7, "Brownies e alfajores", "brownies e alfajores");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (21, 7, "Frutas cristalizadas", "frutas cristalizadas");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (22, 7, "Panettone", "panettone");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (23, 7, "Bolo com frutas", "bolo com frutas");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (24, 7, "Bolos e similares com recheio e/ou cobertura", "bolos e similares com recheio e/ou cobertura");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (25, 7, "Pão croissant, produtos de panificação, salgados ou doces com recheio e ou cobertura", "pao croissant, produtos de panificacao, salgados ou doces com recheio e ou cobertura");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (26, 7, "Snacks a base de cereais e farinhas para petisco", "snacks a base de cereais e farinhas para petisco");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (27, 7, "Mistura para preparo de docinho, cobertura para bolos, tortas e sorvetes, etc.", "mistura para preparo de docinho, cobertura para bolos, tortas e sorvetes, etc.");

INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (1, 8, "Caldo (carne, galinha, legumes, etc) e pós para sopa incluindo (bori-bori, pirá caldo, soyo)", "caldo (carne, galinha, legumes, etc) e pos para sopa incluindo (bori-bori, pira caldo, soyo)");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (2, 8, "Catchup e mostarda", "catchup e mostarda");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (3, 8, "Molhos a base de soja e ou vinagre", "molhos a base de soja e ou vinagre");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (4, 8, "Molhos a base de produtos lácteos ou caldos", "molhos a base de produtos lacteos ou caldos");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (5, 8, "Pós para preparar molhos", "pos para preparar molhos");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (6, 8, "Misso", "misso");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (7, 8, "Missoshiro", "missoshiro");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (8, 8, "Extrato de soja", "extrato de soja");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (9, 8, "Pratos preparados prontos e semiprontos não incluídos em outros itens da tabela", "pratos preparados prontos e semiprontos nao incluidos em outros itens da tabela");
INSERT INTO food_subgroup (id, group_id, description, description_filter) VALUES (10, 8, "Temperos completos", "temperos completos");